import { createHash } from 'crypto';
import { readFileSync, copyFileSync, writeFileSync, readdirSync, unlinkSync } from 'fs';
import { join, extname, basename, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');

function hashFile(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash('md5').update(content).digest('hex').slice(0, 8);
}

function removeOldHashed(dir: string, baseName: string, ext: string) {
  const pattern = new RegExp(`^${baseName}\\.[a-f0-9]{8}${ext.replace('.', '\\.')}$`);
  for (const file of readdirSync(dir)) {
    if (pattern.test(file)) unlinkSync(join(dir, file));
  }
}

function processAsset(srcPath: string): string {
  const ext = extname(srcPath);
  const base = basename(srcPath, ext);
  const dir = srcPath.replace(/\/[^/]+$/, '');
  const hash = hashFile(srcPath);
  const hashedName = `${base}.${hash}${ext}`;
  removeOldHashed(dir, base, ext);
  copyFileSync(srcPath, join(dir, hashedName));
  return hashedName;
}

const cssDir = join(ROOT, 'public/css');
const fontDir = join(ROOT, 'public/fonts/fontawesome');

const cssHashed = processAsset(join(cssDir, 'non-critical.min.css'));
const fontHashed = processAsset(join(fontDir, 'all.min.css'));

const output = `// Auto-generated by scripts/hash-assets.ts — do not edit manually
export const CSS_NON_CRITICAL = '/css/${cssHashed}';
export const CSS_FONTAWESOME = '/fonts/fontawesome/${fontHashed}';
`;

writeFileSync(join(ROOT, 'lib/asset-hashes.ts'), output);

console.log(`✓ ${cssHashed}`);
console.log(`✓ ${fontHashed}`);
