// Asset hashing: generates content-hashed filenames for CSS/font assets
// and writes lib/asset-hashes.ts so Next.js can reference them.
// Pure Node.js — no tsx/TypeScript required.

import { createHash } from 'crypto'
import { readFileSync, copyFileSync, writeFileSync, readdirSync, unlinkSync } from 'fs'
import { join, extname, basename, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

function hashFile(filePath) {
  return createHash('md5').update(readFileSync(filePath)).digest('hex').slice(0, 8)
}

function removeOldHashed(dir, baseName, ext) {
  const pattern = new RegExp(`^${baseName}\\.[a-f0-9]{8}${ext.replace('.', '\\.')}$`)
  for (const file of readdirSync(dir)) {
    if (pattern.test(file)) unlinkSync(join(dir, file))
  }
}

function processAsset(srcPath) {
  const ext = extname(srcPath)
  const base = basename(srcPath, ext)
  const dir = srcPath.replace(/\/[^/]+$/, '')
  const hash = hashFile(srcPath)
  const hashedName = `${base}.${hash}${ext}`
  removeOldHashed(dir, base, ext)
  copyFileSync(srcPath, join(dir, hashedName))
  return hashedName
}

console.log('[build:assets] Hashing CSS and font assets...')

const cssHashed = processAsset(join(ROOT, 'public/css/non-critical.min.css'))
const fontHashed = processAsset(join(ROOT, 'public/fonts/fontawesome/all.min.css'))

writeFileSync(
  join(ROOT, 'lib/asset-hashes.ts'),
  `// Auto-generated by scripts/hash-assets.mjs — do not edit manually\nexport const CSS_NON_CRITICAL = '/css/${cssHashed}';\nexport const CSS_FONTAWESOME = '/fonts/fontawesome/${fontHashed}';\n`,
)

console.log(`[build:assets] css:  ${cssHashed}`)
console.log(`[build:assets] font: ${fontHashed}`)
