// Asset hashing: generates content-hashed filenames for CSS/font assets
// and writes lib/asset-hashes.ts so Next.js can reference them.
// Pure Node.js — no tsx/TypeScript required.

import { createHash } from 'crypto'
import { readFileSync, copyFileSync, writeFileSync, readdirSync, unlinkSync } from 'fs'
import { join, extname, basename, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

function hashFile(filePath) {
  return createHash('md5').update(readFileSync(filePath)).digest('hex').slice(0, 8)
}

function removeOldHashed(dir, baseName, ext) {
  const pattern = new RegExp(`^${baseName}\\.[a-f0-9]{8}${ext.replace('.', '\\.')}$`)
  for (const file of readdirSync(dir)) {
    if (pattern.test(file)) unlinkSync(join(dir, file))
  }
}

function processAsset(srcPath) {
  const ext = extname(srcPath)
  const base = basename(srcPath, ext)
  const dir = srcPath.replace(/\/[^/]+$/, '')
  const hash = hashFile(srcPath)
  const hashedName = `${base}.${hash}${ext}`
  removeOldHashed(dir, base, ext)
  copyFileSync(srcPath, join(dir, hashedName))
  return hashedName
}

console.log('[build:assets] Hashing CSS and font assets...')

const cssHashed = processAsset(join(ROOT, 'public/css/non-critical.min.css'))
// 旧 all.min.<hash>.css の残骸を掃除（現在は subset 版のみ配信）
removeOldHashed(join(ROOT, 'public/fonts/fontawesome'), 'all.min', '.css')
const fontHashed = processAsset(join(ROOT, 'public/fonts/fontawesome/all.subset.min.css'))

// subset-fontawesome.mjs が生成したハッシュ付き woff2 のパスを CSS から抽出し、
// layout.tsx の preload 用にエクスポートする
const subsetCss = readFileSync(join(ROOT, 'public/fonts/fontawesome/all.subset.min.css'), 'utf8')
function extractFontPath(base) {
  const m = subsetCss.match(new RegExp(`/fonts/fontawesome/${base}\\.subset\\.[a-f0-9]{8}\\.woff2`))
  if (!m) throw new Error(`[build:assets] ${base} subset font not found in all.subset.min.css — run scripts/subset-fontawesome.mjs first`)
  return m[0]
}
const faSolid = extractFontPath('fa-solid-900')
const faBrands = extractFontPath('fa-brands-400')

writeFileSync(
  join(ROOT, 'lib/asset-hashes.ts'),
  `// Auto-generated by scripts/hash-assets.mjs — do not edit manually\n` +
    `export const CSS_NON_CRITICAL = '/css/${cssHashed}';\n` +
    `export const CSS_FONTAWESOME = '/fonts/fontawesome/${fontHashed}';\n` +
    `export const FONT_FA_SOLID = '${faSolid}';\n` +
    `export const FONT_FA_BRANDS = '${faBrands}';\n`,
)

console.log(`[build:assets] css:  ${cssHashed}`)
console.log(`[build:assets] font: ${fontHashed}`)
console.log(`[build:assets] woff2: ${faSolid}, ${faBrands}`)
