-- ============================================================
-- Mac（デスクトップ）カテゴリ 一括セットアップSQL
-- Supabase SQL Editor に「ファイル全体を」貼り付けて一度に実行する
-- （テーブル作成と機種データ投入が1ファイルにまとまっているので、
--   一部だけ選択して実行すると relation does not exist で落ちる）
--
-- 順序: mac_models → mac_price_logs → shops列追加 → RLS → 機種データ9件
--
-- 設計方針:
--   iMac / Mac mini / Mac Studio を1テーブルにまとめ、device_type で区別する。
--   MacBook（macbook_models）とはテーブルを分ける。共用にすると
--   getAllMacBookModels() を呼ぶ既存12ページすべてに絞り込みが必要になり、
--   1箇所漏らすとMacBookのスペック表にiMacが混ざる。URLも /macbook/ と /mac/ で
--   分かれているため、同一テーブルだと /macbook/[slug] 側にデスクトップの
--   ページが生成されて重複コンテンツになる。
--
--   ノート固有列（battery / weight / magsafe / promotion / fan）は持たない。
--   代わりにデスクトップ固有列（display_builtin / ethernet /
--   included_accessories / gpu）を持つ。
--
--   価格ログは macbook_price_logs と同じ「全ショップ横断 min1..max5」方式。
--   iosys/geo/janpara 別ではないのは、デスクトップMacが3店舗の在庫だけでは
--   サンプル数を満たせないため（MacBookで同じ判断をしている）。
-- ============================================================


-- ============================================================
-- ① mac_models
-- ============================================================

CREATE TABLE IF NOT EXISTS mac_models (
  id                   INTEGER PRIMARY KEY,
  model                TEXT NOT NULL,           -- 例: 'Mac mini（2024）'
  shortname            TEXT,                    -- 例: 'Mac mini M4'
  slug                 TEXT NOT NULL UNIQUE,    -- 例: 'mac-mini-2024'
  show                 INTEGER NOT NULL DEFAULT 1,
  image                TEXT,
  date                 TEXT,                    -- 発売日 'YYYY/MM/DD'（他カテゴリと表記統一）

  -- 種別（このテーブルの中核。ページの出し分けと相場取得の分岐に使う）
  device_type          TEXT NOT NULL
    CHECK (device_type IN ('imac', 'mac-mini', 'mac-studio')),

  -- 構成
  strage               TEXT,                    -- 例: '256GB ~ 8TB'（既存テーブルに合わせ綴りは strage）
  ram                  TEXT,                    -- 例: '16 / 24 / 32GB'
  color                TEXT,
  cpu                  TEXT,                    -- 例: 'M4 / M4 Pro'
  gpu                  TEXT,                    -- 例: '10コア / 16コア'（Studioは価格差の主因）
  apple_intelligence   BOOLEAN NOT NULL DEFAULT FALSE,

  -- ベンチマーク（macbook_models と同じ3種 + 世代別JSONB）
  score_single         INTEGER,
  score_multi          INTEGER,
  score_metal          INTEGER,
  benchmarks           JSONB,

  -- ディスプレイ（iMac のみ。mini / Studio は NULL）
  display_builtin      BOOLEAN NOT NULL DEFAULT FALSE,
  display              TEXT,                    -- 例: '4.5K Retinaディスプレイ'
  resolution           TEXT,
  luminance            TEXT,

  -- 接続まわり
  -- port は全文。表示には使わず、記録として残しているだけ。
  -- 表示は「どのポートが何基あるか」に分解した下の列を使う。
  -- 値の投入は sql/mac_ports_split.sql を参照。
  port                 TEXT,                    -- 例: 'Thunderbolt4 × 3'
  thunderbolt          TEXT,                    -- 例: '3基'
  thunderbolt_gen      TEXT,                    -- 例: 'Thunderbolt 4（M4 ProはThunderbolt 5）'
  usb_c                TEXT,                    -- 例: '2基'。NULL = 非搭載
  usb_a                TEXT,                    -- 例: '2基'。NULL = 非搭載
  headphone            BOOLEAN NOT NULL DEFAULT FALSE,  -- 3.5mmヘッドフォンジャック
  hdmi                 BOOLEAN NOT NULL DEFAULT FALSE,
  slot                 BOOLEAN NOT NULL DEFAULT FALSE,  -- SDXCカードスロット
  ethernet             TEXT,                    -- 例: 'Gigabit（10Gbは構成オプション）'
  external_display     TEXT,                    -- 台数だけを持つ。例: '3台'、'2台（M2 Proは3台）'

  -- その他
  camera               TEXT,                    -- iMac のみ
  speaker              TEXT,                    -- iMac のみ
  included_accessories TEXT,                    -- 例: 'Magic Keyboard / Magic Mouse'（iMacの実質価格差）
  size                 TEXT,                    -- 筐体寸法 '高さ × 幅 × 奥行き'
  last_macos           TEXT,                    -- サポート終了世代のみ。現役は NULL
                                                -- （createModelQueries の activeField に使う）
  point                TEXT,
  advance              JSONB,
  official             TEXT
);

CREATE INDEX IF NOT EXISTS idx_mac_models_device_type ON mac_models(device_type);

COMMENT ON COLUMN mac_models.device_type IS 'imac / mac-mini / mac-studio。/mac/ 配下のページ出し分けと相場取得キーワードの分岐に使う';
COMMENT ON COLUMN mac_models.display_builtin IS 'ディスプレイ内蔵か。iMacとmini/Studioを分ける最大の比較軸で、おすすめページの比較表の列になる';
COMMENT ON COLUMN mac_models.included_accessories IS 'Magic Keyboard/Mouse 等の同梱物。miniとの実質価格差を出すのに必要';
COMMENT ON COLUMN mac_models.last_macos IS '対応する最後のmacOS。現役モデルはNULL（NULL=現役としてクエリで判定する）';


-- ============================================================
-- ② mac_price_logs
--    macbook_price_logs と同一スキーマ（全ショップ横断 min1..max5）
--    matched_count / matched_prices は最初から入れておく
-- ============================================================

CREATE TABLE IF NOT EXISTS mac_price_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logged_at       DATE NOT NULL,
  model_id        INTEGER NOT NULL REFERENCES mac_models(id),
  model_name      TEXT,
  storage         TEXT,

  min1_price      INTEGER, min1_item_name TEXT, min1_shop_name TEXT,
  min2_price      INTEGER, min2_item_name TEXT, min2_shop_name TEXT,
  min3_price      INTEGER, min3_item_name TEXT, min3_shop_name TEXT,
  min4_price      INTEGER, min4_item_name TEXT, min4_shop_name TEXT,
  min5_price      INTEGER, min5_item_name TEXT, min5_shop_name TEXT,

  max1_price      INTEGER, max1_item_name TEXT, max1_shop_name TEXT,
  max2_price      INTEGER, max2_item_name TEXT, max2_shop_name TEXT,
  max3_price      INTEGER, max3_item_name TEXT, max3_shop_name TEXT,
  max4_price      INTEGER, max4_item_name TEXT, max4_shop_name TEXT,
  max5_price      INTEGER, max5_item_name TEXT, max5_shop_name TEXT,

  matched_count   INTEGER,
  matched_prices  INTEGER[]
);

CREATE INDEX IF NOT EXISTS idx_mac_price_logs_model_id  ON mac_price_logs(model_id);
CREATE INDEX IF NOT EXISTS idx_mac_price_logs_logged_at ON mac_price_logs(logged_at);

COMMENT ON COLUMN mac_price_logs.matched_count IS '相場算出に使用した該当商品数（全ショップ横断）';
COMMENT ON COLUMN mac_price_logs.matched_prices IS '相場算出に使用した全商品の価格（昇順・円、全ショップ横断）。中央値/分布の算出用';


-- ============================================================
-- ③ shops にデスクトップMacの検索URL列を追加
--    未設定のショップは macbook_url にフォールバックする（アプリ側で処理）
-- ============================================================

ALTER TABLE shops
  ADD COLUMN IF NOT EXISTS mac_url TEXT;

COMMENT ON COLUMN shops.mac_url IS 'デスクトップMac（iMac/Mac mini/Mac Studio）の検索URL。NULLなら macbook_url を使う';


-- ============================================================
-- ④ RLS（公開読み取りのみ。既存テーブルと同じポリシー）
--    販売店リンクは既存の product_shop_links を product_type='mac' で共用するため
--    新規テーブルは作らない
-- ============================================================

ALTER TABLE mac_models ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON mac_models;
CREATE POLICY "Allow public read" ON mac_models FOR SELECT USING (true);

ALTER TABLE mac_price_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON mac_price_logs;
CREATE POLICY "Allow public read" ON mac_price_logs FOR SELECT USING (true);


-- ============================================================
-- ⑤ 機種データ（Apple Silicon デスクトップ 全9機種）
--
-- 出典（すべて Apple 公式）:
--   ラインナップの確定 …… apple.com/jp/mac/compare/（現行）＋ 各「モデルを識別する」ページ
--     iMac        https://support.apple.com/ja-jp/108054
--     Mac mini    https://support.apple.com/ja-jp/102852
--     Mac Studio  https://support.apple.com/ja-jp/102231
--   スペック実値 …… 各機種の「技術仕様」ページ（official 列のURL）
--   発売日 …… Apple Newsroom の各プレスリリース記載の出荷開始日
--
-- 2026-08-09 時点で Apple Silicon のデスクトップは iMac 3世代 /
-- Mac mini 3世代 / Mac Studio 3世代の計9機種。M5搭載のデスクトップは
-- 公式には存在しない（噂サイトの情報のみだったため採用していない）。
-- Mac Pro は当サイトの対象外なので入れていない。
--
-- score_single / score_multi / score_metal / benchmarks は Apple が
-- 公表していないため NULL。Geekbench の実測値を別途投入すること。
-- last_macos は全機種 NULL（Apple Silicon はいずれも現行 macOS のサポート内）。
-- image は <slug>.webp。実ファイルの置き場は public/images/mac/。
-- ============================================================


-- ------------------------------------------------------------
-- iMac（id: 1〜3）
-- 24インチはいずれも「2ポートモデル」と「4ポートモデル」があり、
-- CPU/GPUコア数・ストレージ上限・Ethernetの有無が異なる。
-- 中古では両方が同じ「iMac 24インチ（年）」として流通するため1行にまとめ、
-- 差分は各列のテキストで併記する。
-- ============================================================

INSERT INTO mac_models (
  id, model, shortname, slug, show, image, date, device_type,
  strage, ram, color, cpu, gpu, apple_intelligence,
  display_builtin, display, resolution, luminance,
  port, hdmi, slot, ethernet, external_display,
  camera, speaker, included_accessories, size, last_macos, official
) VALUES
(1,
 'iMac 24インチ（2021）', 'iMac 24インチ M1', 'imac-24-2021', 1, 'imac-24-2021.webp', '2021/05/21', 'imac',
 '256GB ~ 2TB', '8 / 16GB',
 'ブルー / グリーン / ピンク / シルバー / イエロー / オレンジ / パープル',
 'M1', '7コア / 8コア', TRUE,
 TRUE, '24インチ4.5K Retinaディスプレイ', '4,480 x 2,520', '500ニト',
 'Thunderbolt / USB 4 × 2（4ポートモデルはUSB 3 × 2を追加）', FALSE, FALSE,
 'ギガビットEthernet（電源アダプタ内蔵。2ポートモデルはオプション）',
 '1台',
 '1080p FaceTime HDカメラ', '6スピーカーシステム（空間オーディオ対応）',
 'Magic Keyboard / Magic Mouse',
 '高さ46.1 × 幅54.7 × 奥行き14.7cm（スタンド含む）', NULL,
 'https://support.apple.com/ja-jp/111895'),

(2,
 'iMac 24インチ（2023）', 'iMac 24インチ M3', 'imac-24-2023', 1, 'imac-24-2023.webp', '2023/11/07', 'imac',
 '256GB ~ 2TB', '8 / 16 / 24GB',
 'ブルー / グリーン / ピンク / シルバー / イエロー / オレンジ / パープル（2ポートモデルは4色）',
 'M3', '8コア / 10コア', TRUE,
 TRUE, '24インチ4.5K Retinaディスプレイ', '4,480 x 2,520', '500ニト',
 'Thunderbolt / USB 4 × 2（4ポートモデルはUSB 3 × 2を追加）', FALSE, FALSE,
 'ギガビットEthernet（電源アダプタ内蔵。2ポートモデルはオプション）',
 '1台',
 '1080p FaceTime HDカメラ', '6スピーカーシステム（空間オーディオ対応）',
 'Touch ID搭載Magic Keyboard / Magic Mouse',
 '高さ46.1 × 幅54.7 × 奥行き14.7cm（スタンド含む）', NULL,
 'https://support.apple.com/ja-jp/117734'),

(3,
 'iMac 24インチ（2024）', 'iMac 24インチ M4', 'imac-24-2024', 1, 'imac-24-2024.webp', '2024/11/08', 'imac',
 '256GB ~ 2TB', '16 / 24 / 32GB',
 'ブルー / パープル / ピンク / オレンジ / イエロー / グリーン / シルバー',
 'M4', '8コア / 10コア', TRUE,
 TRUE, '24インチ4.5K Retinaディスプレイ（Nano-textureガラスオプションあり）', '4,480 x 2,520', '500ニト',
 'Thunderbolt 4 × 4（2ポートモデルはThunderbolt / USB 4 × 2）', FALSE, FALSE,
 'ギガビットEthernet（電源アダプタ内蔵。2ポートモデルはオプション）',
 '2台',
 'デスクビュー対応 12MPセンターフレームカメラ', '6スピーカーシステム（空間オーディオ対応）',
 'Touch ID搭載Magic Keyboard / Magic Mouse',
 '高さ46.1 × 幅54.7 × 奥行き14.7cm（スタンド含む）', NULL,
 'https://support.apple.com/ja-jp/121557');


-- ============================================================
-- Mac mini（id: 4〜6）
-- ============================================================

INSERT INTO mac_models (
  id, model, shortname, slug, show, image, date, device_type,
  strage, ram, color, cpu, gpu, apple_intelligence,
  display_builtin, display, resolution, luminance,
  port, hdmi, slot, ethernet, external_display,
  camera, speaker, included_accessories, size, last_macos, official
) VALUES
(4,
 'Mac mini（2020）', 'Mac mini M1', 'mac-mini-2020', 1, 'mac-mini-2020.webp', '2020/11/17', 'mac-mini',
 '256GB ~ 2TB', '8 / 16GB', 'シルバー',
 'M1', '8コア', TRUE,
 FALSE, NULL, NULL, NULL,
 'Thunderbolt / USB 4 × 2、USB-A × 2、HDMI、3.5mmヘッドフォンジャック', TRUE, FALSE,
 'ギガビットEthernet（10Gb Ethernetに変更可能）',
 '2台（2台目は4Kまで）',
 NULL, '内蔵スピーカー',
 '電源コード',
 '高さ3.6 × 幅19.7 × 奥行き19.7cm', NULL,
 'https://support.apple.com/ja-jp/111894'),

(5,
 'Mac mini（2023）', 'Mac mini M2', 'mac-mini-2023', 1, 'mac-mini-2023.webp', '2023/01/24', 'mac-mini',
 '256GB ~ 8TB', '8 / 16 / 24 / 32GB', 'シルバー',
 'M2 / M2 Pro', '10コア（M2） / 16・19コア（M2 Pro）', TRUE,
 FALSE, NULL, NULL, NULL,
 'Thunderbolt 4 × 2（M2） / × 4（M2 Pro）、USB-A × 2、HDMI、3.5mmヘッドフォンジャック', TRUE, FALSE,
 'ギガビットEthernet（10Gb Ethernetに変更可能）',
 '2台（M2 Proは3台）',
 NULL, '内蔵スピーカー',
 '電源コード',
 '高さ3.58 × 幅19.70 × 奥行き19.70cm', NULL,
 'https://support.apple.com/ja-jp/111837'),

(6,
 'Mac mini（2024）', 'Mac mini M4', 'mac-mini-2024', 1, 'mac-mini-2024.webp', '2024/11/08', 'mac-mini',
 '256GB ~ 8TB', '16 / 24 / 32 / 48 / 64GB', 'シルバー',
 'M4 / M4 Pro', '10コア（M4） / 16・20コア（M4 Pro）', TRUE,
 FALSE, NULL, NULL, NULL,
 '前面: USB-C × 2、3.5mmヘッドフォンジャック / 背面: Thunderbolt 4 × 3（M4）またはThunderbolt 5 × 3（M4 Pro）、HDMI、Ethernet', TRUE, FALSE,
 'ギガビットEthernet（10Gb Ethernetに変更可能）',
 '3台',
 NULL, '内蔵スピーカー',
 '電源コード（1.8m）',
 '高さ5.0 × 幅12.7 × 奥行き12.7cm', NULL,
 'https://support.apple.com/ja-jp/121555');


-- ============================================================
-- Mac Studio（id: 7〜9）
-- 前面ポートはチップで異なる（Max は USB-C、Ultra は Thunderbolt）。
-- SDXCカードスロットは全世代に標準搭載。
-- ============================================================

INSERT INTO mac_models (
  id, model, shortname, slug, show, image, date, device_type,
  strage, ram, color, cpu, gpu, apple_intelligence,
  display_builtin, display, resolution, luminance,
  port, hdmi, slot, ethernet, external_display,
  camera, speaker, included_accessories, size, last_macos, official
) VALUES
(7,
 'Mac Studio（2022）', 'Mac Studio M1 Max', 'mac-studio-2022', 1, 'mac-studio-2022.webp', '2022/03/18', 'mac-studio',
 '512GB ~ 8TB', '32 / 64 / 128GB', 'シルバー',
 'M1 Max / M1 Ultra', '24・32コア（M1 Max） / 48・64コア（M1 Ultra）', TRUE,
 FALSE, NULL, NULL, NULL,
 '背面: Thunderbolt 4 × 4、USB-A × 2、HDMI、10Gb Ethernet、3.5mm / 前面: USB-C × 2（M1 Max）またはThunderbolt 4 × 2（M1 Ultra）、SDXC', TRUE, TRUE,
 '10Gb Ethernet',
 '5台',
 NULL, '内蔵スピーカー',
 '電源コード',
 '高さ9.5 × 幅19.7 × 奥行き19.7cm', NULL,
 'https://support.apple.com/ja-jp/111900'),

(8,
 'Mac Studio（2023）', 'Mac Studio M2 Max', 'mac-studio-2023', 1, 'mac-studio-2023.webp', '2023/06/13', 'mac-studio',
 '512GB ~ 8TB', '32 / 64 / 96 / 128 / 192GB', 'シルバー',
 'M2 Max / M2 Ultra', '30・38コア（M2 Max） / 60・76コア（M2 Ultra）', TRUE,
 FALSE, NULL, NULL, NULL,
 '背面: Thunderbolt 4 × 4、USB-A × 2、HDMI、10Gb Ethernet、3.5mm / 前面: USB-C × 2（M2 Max）またはThunderbolt 4 × 2（M2 Ultra）、SDXC', TRUE, TRUE,
 '10Gb Ethernet',
 '5台（M2 Ultraは8台）',
 NULL, '内蔵スピーカー',
 '電源コード',
 '高さ9.5 × 幅19.7 × 奥行き19.7cm', NULL,
 'https://support.apple.com/ja-jp/111835'),

(9,
 'Mac Studio（2025）', 'Mac Studio M4 Max', 'mac-studio-2025', 1, 'mac-studio-2025.webp', '2025/03/12', 'mac-studio',
 '512GB ~ 16TB', '36 / 48 / 64 / 96 / 128 / 256GB', 'シルバー',
 'M4 Max / M3 Ultra', '32・40コア（M4 Max） / 60・80コア（M3 Ultra）', TRUE,
 FALSE, NULL, NULL, NULL,
 '背面: Thunderbolt 5 × 4、USB-A × 2、HDMI 2.1、10Gb Ethernet、3.5mm / 前面: USB-C × 2（M4 Max）またはThunderbolt 5 × 2（M3 Ultra）、SDXC', TRUE, TRUE,
 '10Gb Ethernet',
 '5台（M3 Ultraは8台）',
 NULL, '内蔵スピーカー',
 '電源コード',
 '高さ9.5 × 幅19.7 × 奥行き19.7cm', NULL,
 'https://support.apple.com/ja-jp/122211');


-- 確認用
-- SELECT id, model, device_type, date, cpu, gpu FROM mac_models ORDER BY id;
