-- ============================================================
-- Pixel Price Logs テーブル作成
-- iphone_price_logs と同じ3店舗（イオシス・ゲオ・じゃんぱら）構成。
-- 価格収集 cron（Vultr）側で pixel 対応後に日次 INSERT される想定。
-- ============================================================

CREATE TABLE IF NOT EXISTS pixel_price_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logged_at     DATE NOT NULL,
  model_id      INTEGER NOT NULL REFERENCES pixel_models(id),
  model_name    TEXT,
  storage       TEXT,
  iosys_min     INTEGER,
  iosys_max     INTEGER,
  geo_min       INTEGER,
  geo_max       INTEGER,
  janpara_min   INTEGER,
  janpara_max   INTEGER,
  iosys_min_text  TEXT,
  iosys_max_text  TEXT,
  geo_min_text    TEXT,
  geo_max_text    TEXT,
  janpara_min_text TEXT,
  janpara_max_text TEXT
);

CREATE INDEX IF NOT EXISTS idx_pixel_price_logs_model_id ON pixel_price_logs(model_id);
CREATE INDEX IF NOT EXISTS idx_pixel_price_logs_logged_at ON pixel_price_logs(logged_at);

-- RLS（公開読み取りのみ）
ALTER TABLE pixel_price_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON pixel_price_logs;
CREATE POLICY "Allow public read" ON pixel_price_logs FOR SELECT USING (true);
